version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install & npm install -g wait-on
      - run:
          name: Run local server
          command: npm run serve & wait-on http://localhost:8080
      - run:
          name: Run cypress e2e tests
          command: cypress run
