version: 2.1
jobs:
  build:
    working_directory: ~/transport
    docker:
      - image: cypress/included:3.2.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/transport
          paths:
            - .
  tests_e2e:
    working_directory: ~/transport
    docker:
      - image: cypress/included:3.2.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/transport
      - run:
          name: Run e2e tests
          command: npm run test:e2e -- --headless
workflows:
  workflow:
    jobs:
      - build
      - tests_e2e