version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install & npm install wait-on & npm install -g @vue/cli-service
      - run:
          name: Run local server
          command: npm run serve & npx wait-on http://localhost:8080
      - run:
          name: Run cypress e2e tests
          command: $(npm bin)/cypress run
