version: 2.1

defaults: &defaults
  docker:
    - image: cypress/included:3.2.0
      environment:
        ## this enables colors in the output
        TERM: xterm

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
  e2e cypress tests:
    build:
      <<: *defaults
    steps:
      - run:
          name: Run tests
          command: npm run test:e2e -- --headless

